export const ADD_COMMENT_TO_POST_START = 'ADD_COMMENT_TO_POST_START'
export const ADD_COMMENT_TO_POST_SUCCESS = 'ADD_COMMENT_TO_POST_SUCCESS'
export const ADD_COMMENT_TO_POST_FAIL = 'ADD_COMMENT_TO_POST_FAIL'

export const REMOVE_COMMENT_FROM_POST_START = 'REMOVE_COMMENT_FROM_POST_START'
export const REMOVE_COMMENT_FROM_POST_SUCCESS = 'REMOVE_COMMENT_FROM_POST_SUCCESS'
export const REMOVE_COMMENT_FROM_POST_FAIL = 'REMOVE_COMMENT_FROM_POST_FAIL'

export const EDIT_COMMENT_START = 'EDIT_COMMENT_START'
export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS'
export const EDIT_COMMENT_FAIL = 'EDIT_COMMENT_FAIL'