export const POST_CREATE_START = 'POST_CREATE_START';
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';
export const POST_CREATE_FAIL = 'POST_CREATE_FAIL';

export const GET_ALL_POST_START = 'GET_ALL_POST_START';
export const GET_ALL_POST_SUCCESS = 'GET_ALL_POST_SUCCESS';
export const GET_ALL_POST_FAIL = 'GET_ALL_POST_FAIL';


export const ADD_COMMENT_TO_POST_START = 'ADD_COMMENT_TO_POST_START'
export const ADD_COMMENT_TO_POST_SUCCESS = 'ADD_COMMENT_TO_POST_SUCCESS'
export const ADD_COMMENT_TO_POST_FAIL = 'ADD_COMMENT_TO_POST_FAIL'

export const REMOVE_COMMENT_TO_POST_START = 'REMOVE_COMMENT_TO_POST_START'
export const REMOVE_COMMENT_TO_POST_SUCCESS = 'REMOVE_COMMENT_TO_POST_SUCCESS'
export const REMOVE_COMMENT_TO_POST_FAIL = 'REMOVE_COMMENT_TO_POST_FAIL'

export const EDIT_COMMENT_TO_POST_START = 'EDIT_COMMENT_TO_POST_START'
export const EDIT_COMMENT_TO_POST_SUCCESS = 'EDIT_COMMENT_TO_POST_SUCCESS'
export const EDIT_COMMENT_TO_POST_FAIL = 'EDIT_COMMENT_TO_POST_FAIL'