export const NOTIFICATION = 'NOTIFICATION';
export const MESSAGE = 'MESSAGE';

export const RECEIVE_MESSAGE_START = 'RECEIVE_MESSAGE_START';
export const RECEIVE_MESSAGE_SUCCESS = 'RECEIVE_MESSAGE_SUCCESS';

// Types of notification in our app
export const RECEIVE_NOTIFICATION_START = 'RECEIVE_NOTIFICATION_START';

export const RECEIVE_ADD_FRIEND_REQUEST = 'RECEIVE_ADD_FRIEND_REQUEST';
export const RECEIVE_LIKE_POST = 'RECEIVE_LIKE_POST';
export const RECEIVE_COMMENT = 'RECEIVE_COMMENT';
export const RECEIVE_FRIEND_ACCEPTED = 'RECEIVE_FRIEND_ACCEPTED';