export const GET_BASIC_USER_INFOR_START = 'GET_BASIC_USER_INFOR_START';
export const GET_BASIC_USER_INFOR_SUCCESS = 'GET_BASIC_USER_INFOR_SUCCESS';
export const GET_BASIC_USER_INFOR_FAIL = 'GET_BASIC_USER_INFOR_FAIL';


export const GET_POST_OF_USER_START = 'GET_POST_OF_USER_START';
export const GET_POST_OF_USER_SUCCESS = 'GET_POST_OF_USER_SUCCESS';
export const GET_POST_OF_USER_FAIL = 'GET_POST_OF_USER_FAIL';